[[language]]
name = "bash"
indent = { tab-width = 4, unit = "    " }
#        '-sr',  # redirect operators will be followed by a space
#        '-i=4',  # indent with four spaces
formatter = { command = 'shfmt', args = ["-sr", "-i=4"] }
auto-format = true

[[language]]
name = "python"
language-servers = ["ruff", "pylsp", "codebook"]
auto-format = true

[[language]]
name = "markdown"
language-servers = ["codebook"]

[[language]]
name = "rst"
language-servers = ["codebook"]

[language-server.pylsp.config.pylsp.plugins]
flake8 = {enabled = false}
autopep8 = {enabled = false}
mccabe = {enabled = false}
pycodestyle = {enabled = false}
pyflakes = {enabled = false}
pylint = {enabled = false}
yapf = {enabled = false}
ruff = {enabled = false}

[language-server.codebook]
command = "codebook-lsp"
args = ["serve"]
